[supervisord]
logfile=/home/quannh/projects_de/project_2/logs/supervisord.log
loglevel=info
pidfile=/home/quannh/projects_de/project_2/configs/supervisord.pid
childlogdir=/home/quannh/projects_de/project_2/logs

[program:crawl]
command=/usr/bin/python3 -m src.main
directory=/home/quannh/projects_de/project_2
autostart=true
autorestart=unexpected
stderr_logfile=/dev/null
stdout_logfile=/dev/null

[unix_http_server]
file=/home/quannh/projects_de/project_2/configs/supervisor.sock   ; socket file

[supervisorctl]
serverurl=unix:///home/quannh/projects_de/project_2/configs/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
